### ISSUE TITLE
check_any_word_args: consider all the wait_for_response nodes in the flows

### ISSUE THREAD

**Issue by fagiothree** [fagiothree/idems_translation#14]
The script should consider all the wait_for_response (or more in general switch nodes, see https://app.rapidpro.io/mr/docs/routing.html), irrespective of the fact that they have a send_message node with quick replies as a parent (quick replies are never used in the sanity check process)

**Comment by edmoss94** [comment]
Ok understood, so shall I just get the code to look for everywhere there is an argument with type 'has_any_word'? I think this is how I originally wrote it but I changed to using the quick replies as it was giving me less errors.

**Comment by fagiothree** [comment]
yes I think so. Basically every time there is a split, we should check there is no overlap between the arguments of the different cases. What do you mean by less errors exactly? What type of errors were you getting?

**Comment by edmoss94** [comment]
Errors are probably the wrong word, but I need to consider a few more edge cases if I take all the 'has_any_word' arguments. Using the quick_reply reference was easier because I could safely assume that everything had to have a translation. What I found is there are quite a few nodes which have mostly numerical arguments but then a single 'has_any_word' argument for the NA case. So I dont think those nodes are included in the translation file and my script was saying there was an error for a missing translation which wasn't really the case. Not a major problem, should be a relatively easy fix in the code.

**Comment by edmoss94** [comment]
I am also conscious that this function only tackles 'has_any_words' problems, when in fact we could have problems with all the argument types (eg.has_phrase). However, I think this is ok as any further errors will get picked up in the 'check_integrity' function. It makes sense for now to keep 'has_any_words' check separate as we have an easy way to identify and fix the problem. Maybe once I have come up with a few more 'automated' solutions we can maybe group them together. So the end goal is that we have one function that does as many automatic repairs as possible, and another function which reports any remaining errors

**Comment by fagiothree** [comment]
I see. Yes then we should probably consider only the arguments corresponding to the test cases "has_any_word", "has_all_words", "has_only_phrase", "has_phrase" for now? There are much more cases in here https://app.rapidpro.io/mr/docs/routing.html#tests, but these are the ones used in the flows, so it's a good starting point I guess

**Comment by edmoss94** [comment]
Code has been modified to look for every instance where we 'have_any_word' arguments and apply the fix. If the fix results in the removal of the entire argument then the code will not apply the replacement but this will be clearly recorded in the log file.
